[package]
name = "axum-required-headers-macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3.4.0"
proc-macro2 = "1"
quote = "1"
syn = { version = "2" }
