[package]
name = "axum-required-headers-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3.4.0"
proc-macro2 = "1"
quote = "1"
syn = { version = "2" }
